### ISSUE TITLE
error: ambiguous use of 'lint'

### ISSUE THREAD

**Issue by 417-72KI** [danger/swift#621]
```
/tmp/danger/CE34311C-313A-4804-B754-63A879562477/_tmp_dangerfile.swift:527:15: error: ambiguous use of 'lint'
    SwiftLint.lint(inline: true)
              ^
Danger.SwiftLint:13:24: note: found this candidate
    public static func lint(inline: Bool = false, directory: String? = nil, configFile: String? = nil, strict: Bool = false, quiet: Bool = true, lintAllFiles: Bool = false, swiftlintPath: String? = nil) -> [Danger.SwiftLintViolation]
                       ^
Danger.SwiftLint:18:24: note: found this candidate
    public static func lint(_ lintStyle: Danger.SwiftLint.LintStyle = .modifiedAndCreatedFiles(directory: nil), inline: Bool = false, configFile: String? = nil, strict: Bool = false, quiet: Bool = true, swiftlintPath: Danger.SwiftLint.SwiftlintPath? = nil, markdownAction: (String) -> Void = markdown) -> [Danger.SwiftLintViolation]
                       ^
�[31mERROR: Dangerfile eval failed at Dangerfile.swift
�[0;0m�[31mERROR: Could not get the results JSON file at /tmp/danger/CE34311C-313A-4804-B754-63A879562477/danger-response.json
�[0;0m
```

It seems to be caused by #610 and removing deprecated function ( `lint(..., lintAllFiles:..)` ) may be solve this 🤔

**Comment by npj008** [comment]
Facing same issue. Broken danger check pipeline. @f-meloni is there any way to install particular version of danger-swift using brew?  'tap/' is taking latest one only.
