### ISSUE TITLE
Xcode 14.3 / Swift 5.8 isn't supported

### ISSUE THREAD

**Issue by oronbz** [danger/swift#581]
After installing `danger-swift` from `homebrew` via: `brew install danger/tap/danger-swift `
and running: `danger-swift ci`

I'm getting an error: 
`/var/folders/xq/sfn_fz953jb36ptp2g68wc2r0000gn/T/danger/23DCD1B6-C155-4C21-AA12-07C23FD17199/_tmp_dangerfile.swift:1:8: error: compiled module was created by a different version of the compiler; rebuild 'Danger' and try again: /usr/local/lib/danger/Danger.swiftmodule`

Xcode 14.3 / Swift 5.8

Works perfectly on Xcode 14.2 / Swift 5.7 environment

**Comment by f-meloni** [comment]
Did you install it with the new Xcode selected? Brew compiles danger with your Xcode, so if you had the old Xcode selected then it was compiled from that Xcode and it fails when you switch to a different version.

**Comment by oronbz** [comment]
It's running from CI (Bitrise) and the stack is already configured with Xcode 14.3 only.
