### ISSUE TITLE
Danger Swift does not work on Xcode 16 even with v3.21.1

### ISSUE THREAD

**Issue by stotic-dev** [danger/swift#642]
## 💡 Summary
When trying to run Danger Swift locally using SwiftPM, I encountered an instantiation error with `Danger()`, preventing Danger from working properly.  
This issue seems similar to the following ones, but it still occurs even when using the latest version:  
- danger/swift#615  
- danger/swift#623  

Additionally, it works fine in an Xcode 15 & Swift 5.9 environment.  
I have listed my current setup below. Is there something incorrect with my configuration?  

## 📌 Local Environment
- Xcode: **16.2**  
- Swift: **6.0.3**  
- Danger Swift: 3.21.1  
- OS: **macOS (M1) 15.0**  

## 🚀 Execution Command 
```sh
 % swift run danger-swift pr https://github.com/FujimoriGit/AkiraDiary/pull/66 --verbose
Building for debugging...
[1/1] Write swift-version-7ECE0B649383FE20.txt
Build of product 'danger-swift' complete! (0.21s)
Launching Danger Swift pr (v3.21.1)
Finding out where the danger executable is
Running: file:///Users/satoutaichi/.nvm/versions/node/v18.16.0/bin/danger pr --process .build/debug/danger-swift --passURLForDSL https://github.com/FujimoriGit/AkiraDiary/pull/66 --verbose 
Starting Danger PR on FujimoriGit/AkiraDiary#66
/var/folders/dz/_vzvz7yn6hg_by51jhrw1tz80000gn/T/danger/1BD903F2-7722-42D5-9652-0EB1ACEE81F8/_tmp_dangerfile.swift:3:14: error: cannot call value of non-function type 'module<Danger>'
1 | import Danger
2 | 
3 | let danger = Danger()
  |              `- error: cannot call value of non-function type 'module<Danger>'
4 | 

Launching Danger Swift runner (v3.21.1)
Got URL for JSON: /var/folders/dz/_vzvz7yn6hg_by51jhrw1tz80000gn/T/danger-dsl-9a0fe2f4.json
Created a temporary file for the Dangerfile DSL at: /var/folders/dz/_vzvz7yn6hg_by51jhrw1tz80000gn/T/danger-dsl-9a0fe2f4.json
Running Dangerfile at: Dangerfile.swift
Preparing to compile
Running: /Applications/Xcode16.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift --driver-mode=swift -L /Users/satoutaichi/work/swift/DangerSwiftModule/Dangerfile/.build/debug -I /Users/satoutaichi/work/swift/DangerSwiftModule/Dangerfile/.build/debug -lDanger /var/folders/dz/_vzvz7yn6hg_by51jhrw1tz80000gn/T/danger/1BD903F2-7722-42D5-9652-0EB1ACEE81F8/_tmp_dangerfile.swift runner /Users/satoutaichi/.nvm/versions/node/v18.16.0/lib/node_modules/danger/distribution/commands/danger-pr.js --process .build/debug/danger-swift --passURLForDSL https://github.com/FujimoriGit/AkiraDiary/pull/66 --verbose /var/folders/dz/_vzvz7yn6hg_by51jhrw1tz80000gn/T/danger-dsl-9a0fe2f4.json /var/folders/dz/_vzvz7yn6hg_by51jhrw1tz80000gn/T/danger/1BD903F2-7722-42D5-9652-0EB1ACEE81F8/danger-response.json
Completed evaluation
ERROR: Dangerfile eval failed at Dangerfile.swift
ERROR: Could not get the results JSON file at /var/folders/dz/_vzvz7yn6hg_by51jhrw1tz80000gn/T/danger/1BD903F2-7722-42D5-9652-0EB1ACEE81F8/danger-response.json

keyNotFound(CodingKeys(stringValue: "tagName", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"tagName\", intValue: nil) (\"tagName\").", underlyingError: nil))
```

## Package.swift
```swift
// swift-tools-version: 6.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "Dangerfile",
    products: [
        .library(name: "Danger", type: .dynamic, targets: ["Dangerfile"]),
    ],
    dependencies: [.package(url: "https://github.com/danger/swift.git", exact: "3.21.1")],
    targets: [
        .target(name: "Dangerfile", dependencies: [.product(name: "Danger", package: "swift")]),
    ]
)
```

## Dangerfile
```swift
import Danger

let danger = Danger()
```

**Comment by stotic-dev** [comment]
After modifying Package.swift as follows, 'swift run danger-swift pr <PR url>' started working.
 Additionally, 'swift run danger-swift ci' now works in the CI environment as well.

```diff
// swift-tools-version: 6.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "Dangerfile",
    products: [
-      .library(name: "Danger", type: .dynamic, targets: ["Dangerfile"]),
+       .library(name: "DangerDeps", type: .dynamic, targets: ["Dangerfile"]),
    ],
    dependencies: [.package(url: "https://github.com/danger/swift.git", exact: "3.21.1")],
    targets: [
        .target(name: "Dangerfile", dependencies: [.product(name: "Danger", package: "swift")]),
    ]
)
```
